#!/usr/bin/env python3
# THE FOUR SHELLS. app.html is the one that is written; these are struck from it.
#
# /gift, /p/:slug, /passage and /guided are shareable and used to unfurl with the
# landing's picture and the landing's sentence on them. A gift arriving in a message
# with somebody else's title on it does not get opened. Each carries its own face now,
# cut from one of his scenes.
#
#   python3 scripts/shells.py
import io, os, re
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/'
FACES = {'gift': ('Somebody grew this for you', 'A Gratus gift carries the days it took. Open it and see what they wrote.'), 'p': ('How this project answers', 'The people who gave, the words they sent, and what the project said back.'), 'passage': ('The Passage', 'A room, a code, and a few people saying out loud what they are grateful for.'), 'guided': ('Gratus Guides', 'Why any of this exists, and how to walk it.')}
app = io.open(R + 'app.html', encoding='utf-8').read()
for key, (title, desc) in FACES.items():
    h = re.sub(r'<meta property="og:title" content="[^"]*"', '<meta property="og:title" content="' + title + '"', app, count=1)
    h = re.sub(r'<meta property="og:description" content="[^"]*"', '<meta property="og:description" content="' + desc + '"', h, count=1)
    h = re.sub(r'<meta property="og:image" content="[^"]*"', '<meta property="og:image" content="https://www.gratus.cc/assets/brand/og/' + key + '.jpg"', h, count=1)
    h = h.replace('<title>Gratus.CC</title>', '<title>' + title + ' \u00b7 Gratus.CC</title>')
    h = h.replace('<!doctype html>', '<!doctype html>\n<!-- The same shell as app.html, with this route\'s own face on it. Generated by\n     scripts/shells.py; edit app.html and run that, never this file. -->')
    if key == 'guided':
        # the guide list is static so that /guided reads with no JavaScript at all
        import glob
        rows = []
        for f in sorted(glob.glob(R + 'docs/guides/*.md')):
            body = io.open(f, encoding='utf-8').read()
            slug = os.path.basename(f)[:-3]
            title = re.search(r'^title:\s*(.+)$', body, re.M).group(1).strip()
            aud = re.search(r'^audience:\s*(.+)$', body, re.M).group(1).strip()
            mins = re.search(r'^time:\s*(.+)$', body, re.M).group(1).strip()
            rows.append('      <li><a href="https://github.com/InitiumBuilders/Gratus.CC-Open/blob/master/docs/guides/' + slug + '.md"><b>' + title + '</b><span>' + aud + ' \u00b7 ' + mins + '</span></a></li>')
        block = '\n<main id="guided-index">\n  <h1>Gratus Guides</h1>\n  <p>Why any of this exists, and how to walk it. ' + str(len(rows)) + ' guides, each one checked against the\n     build it names.</p>\n  <ul>\n' + '\n'.join(rows) + '\n  </ul>\n</main>\n'
        h = h.replace('<main id="view"></main>', '<main id="view"></main>' + block, 1)
    t = R + key + '.html.tmp'
    io.open(t, 'w', encoding='utf-8', newline='\n').write(h)
    os.replace(t, R + key + '.html')
    print('wrote', key + '.html')
